//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejercicio4_a171291.calcular {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="calcular.calculoSoap")]
    public interface calculoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Ejercicio4_a171291.calcular.HelloWorldResponse HelloWorld(Ejercicio4_a171291.calcular.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Ejercicio4_a171291.calcular.HelloWorldResponse> HelloWorldAsync(Ejercicio4_a171291.calcular.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cuadrado", ReplyAction="*")]
        double cuadrado(double L1, double L2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cuadrado", ReplyAction="*")]
        System.Threading.Tasks.Task<double> cuadradoAsync(double L1, double L2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Triangulo", ReplyAction="*")]
        double Triangulo(double B, double A);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Triangulo", ReplyAction="*")]
        System.Threading.Tasks.Task<double> TrianguloAsync(double B, double A);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/circulo", ReplyAction="*")]
        double circulo(double Radio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/circulo", ReplyAction="*")]
        System.Threading.Tasks.Task<double> circuloAsync(double Radio);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Ejercicio4_a171291.calcular.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Ejercicio4_a171291.calcular.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ejercicio4_a171291.calcular.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Ejercicio4_a171291.calcular.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface calculoSoapChannel : Ejercicio4_a171291.calcular.calculoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class calculoSoapClient : System.ServiceModel.ClientBase<Ejercicio4_a171291.calcular.calculoSoap>, Ejercicio4_a171291.calcular.calculoSoap {
        
        public calculoSoapClient() {
        }
        
        public calculoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public calculoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calculoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calculoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ejercicio4_a171291.calcular.HelloWorldResponse Ejercicio4_a171291.calcular.calculoSoap.HelloWorld(Ejercicio4_a171291.calcular.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Ejercicio4_a171291.calcular.HelloWorldRequest inValue = new Ejercicio4_a171291.calcular.HelloWorldRequest();
            inValue.Body = new Ejercicio4_a171291.calcular.HelloWorldRequestBody();
            Ejercicio4_a171291.calcular.HelloWorldResponse retVal = ((Ejercicio4_a171291.calcular.calculoSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ejercicio4_a171291.calcular.HelloWorldResponse> Ejercicio4_a171291.calcular.calculoSoap.HelloWorldAsync(Ejercicio4_a171291.calcular.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ejercicio4_a171291.calcular.HelloWorldResponse> HelloWorldAsync() {
            Ejercicio4_a171291.calcular.HelloWorldRequest inValue = new Ejercicio4_a171291.calcular.HelloWorldRequest();
            inValue.Body = new Ejercicio4_a171291.calcular.HelloWorldRequestBody();
            return ((Ejercicio4_a171291.calcular.calculoSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public double cuadrado(double L1, double L2) {
            return base.Channel.cuadrado(L1, L2);
        }
        
        public System.Threading.Tasks.Task<double> cuadradoAsync(double L1, double L2) {
            return base.Channel.cuadradoAsync(L1, L2);
        }
        
        public double Triangulo(double B, double A) {
            return base.Channel.Triangulo(B, A);
        }
        
        public System.Threading.Tasks.Task<double> TrianguloAsync(double B, double A) {
            return base.Channel.TrianguloAsync(B, A);
        }
        
        public double circulo(double Radio) {
            return base.Channel.circulo(Radio);
        }
        
        public System.Threading.Tasks.Task<double> circuloAsync(double Radio) {
            return base.Channel.circuloAsync(Radio);
        }
    }
}
